### ISSUE TITLE
password change inconsistency

### ISSUE THREAD

**Issue by wadewachs** [HTBox/crisischeckin#178]
When going through the initial registration the password field is compared against a regex pattern for a-z 0-9 and a few unicode characters.
post logging in to change the password doesn't conform to any character constraints other than min->max value.

Password requirements are inconsistent.

**Comment by asherw** [comment]
May I suggest a simpler solution to move forward?

The password properties on both models have no form of actual input string validation.
Shall we create a new custom attribute that we place against the password properties?

This way we can place a unit test against the attribute (the item doing the string validation), rather than the whole process of registering a person or change password process, as this is the actual item in the execution doing the validation.

We can create separate unit tests for the other 2 processes.

**Comment by BillWagner** [comment]
@asherw I really like this idea! Do you want to take this on and implement it?

**Comment by asherw** [comment]
Cool, pull request submitted.

I have created the new attribute
* thrown it onto the appropriate properties on the required models
* created some unit tests for the attribute
* tested it locally on the website

Please note, it does not fail on blank strings, I leave this up to the Required attribute.

**Comment by tonysurma** [comment]
Thanks for jumping in.  I love the approach.

**Comment by asherw** [comment]
No worries.

I saw mentioned above that AccountControllerTests was commented out.  I've reworked it and got it back to a usable state.

I extended IWebSecurityWrapper, and updated it with what was needed to get the unit tests that were already created, working.
I also cleaned the unit tests up and created a small framework (exaggerated use of the word), to allow additional tests to be created for AccountController, and easier building of other controller unit tests.

I couldn't figure out how to do a separate pull request... it seems to only allow me to do 1 per project?

**Comment by tonysurma** [comment]
Quick thought from phone. Yeah I believe only one is correct but you can add to the pull request while it is outstanding

**Comment by asherw** [comment]
Ah ok cheers.  Still learning this whole git life cycle.

**Comment by BillWagner** [comment]
Fix in PR #242
