### ISSUE TITLE
"Remember Me?" does not appear to keep credentials

### ISSUE THREAD

**Issue by wadewachs** [HTBox/crisischeckin#182]
I logged in as "administrator" with "Remember Me?" checked. When I logged out, the Username and password fields were left blank.

RememberMe is getting passed twice on the login page and the values are not the same all the time. Attached picture.
![rememberme](https://cloud.githubusercontent.com/assets/4061222/3386295/079e6798-fc73-11e3-9b49-d02532885888.png)

**Comment by tditiecher** [comment]
The fact that RememberMe is posted twice seems to be how MVC CheckBox is designed (see http://stackoverflow.com/questions/2697299/asp-net-mvc-why-is-html-checkbox-generating-an-additional-hidden-input) and when you debug the AccountController.Login method the RememberMe boolean correctly has the value true.

The remember me option correctly sets a cookie so that if you close the browser without logging out the next time you go to the site you don't have to login again (at least within the timeframe of the cookie). This functionality is working correctly.

The behaviour that the login form is pre-filled with previous credentials normally is functionality of the browser itself and not of the application.

I think this is not a bug but another expectation of what the 'remember me' checkbox should do.

**Comment by BillWagner** [comment]
@tditiecher Good analysis. I will close.
