### ISSUE TITLE
email not sending from dev environment

### ISSUE THREAD

**Issue by wadewachs** [HTBox/crisischeckin#191]
This may just be fallout of the environment we were testing on, but trying to use the function to send e-mail to volunteers was not actually sending e-mail.

**Comment by tditiecher** [comment]
@BillWagner It seems that this issue can be closed as it is fixed by TravCav with PR #241 when working on #235 (Email Sending needs full testing/fixing in dev using test tool).
When running the application in debug mode the emails that are created to be sent are written to files in [the AppData directory of the current user](https://github.com/HTBox/crisischeckin/blob/master/crisischeckin/crisicheckinweb/App_Start/NinjectWebCommon.cs#L81-84) by the SmtpClient as the [deliverymethod is set to SpecifiedPickupDirectory](https://github.com/HTBox/crisischeckin/blob/master/crisischeckin/crisicheckinweb/Web.config#L36) and never 'really sent'.

**Comment by BillWagner** [comment]
Closed per discussion and examination.
