### ISSUE TITLE
SmtpMessageSender is not using injected SmtpSettings

### ISSUE THREAD

**Issue by tditiecher** [HTBox/crisischeckin#245]
It seems that the SmtpSettings injected into the SmtpMessageSender should be used to create the from-address: https://github.com/HTBox/crisischeckin/blob/master/crisischeckin/Services/SmtpMessageSender.cs#L31

In NinjectWebCommon a SmtpSettings object is defined in release mode but it is never used:
https://github.com/HTBox/crisischeckin/blob/master/crisischeckin/crisicheckinweb/App_Start/NinjectWebCommon.cs#L83-L87

What is the idea here?

**Comment by BillWagner** [comment]
Well, this is an artifact of a few different thoughts on how to handle debugging, staging, and release.  Some of the discussion is in issue #235 

At first, we thought that using a directory when DEBUG was defined would be sufficient.  However, as we worked through the workflow, that fails for our public testing / staging site. On that site, we run the latest code and encourage test professionals to explore the site. Because it is meant as an open test site, the admin account uses the default values (from the code in the repo). Given that, we want to ensure that we can test mail functionality on the live testing site without sending actual mail. That caused us to re-examine the old design, and start moving toward a design that would inject the SMTP capabilities, and provide proper testing on the staging site, along with the security necessary to avoid being a vector for sending spam emails. 

So, we'd like to continue moving forward toward the injected settings, and the capabilities you are adding.
