### ISSUE TITLE
Refactor WebAPI EntitiesController to use the service layer.

### ISSUE THREAD

**Issue by tditiecher** [HTBox/crisischeckin#282]
As mentioned in #258 the functionality should use the service layer instead of implementing the functionality directly.

**Comment by brunck** [comment]
@tditiecher  That is not how Breeze works. It uses a proxy of the DbContext. If we are to get rid of this we will have to replace Breeze as our WebAPI. This is OK with me, but please notice that the WebAPI issue is assigned to me and there is discussion there. That issue is in progress. Replacing what we have will take a bit of work but not a ton, but I didn't want to do that on a whim.
I suggest we close this item #282 and resume the discussion on the WebAPI issue thread. We may want to repace Breeze with a more typical REST API that uses our service layer for mobile assembly size reasons.

**Comment by tditiecher** [comment]
@brunck It's okay for me to close this issue as you suggest. I just wanted to keep that part out of issue #258. I will not touch the EntitiesController.

**Comment by brunck** [comment]
Closing #258.
