### ISSUE TITLE
The SMTP server requires a secure connection or the client was not authenticated.

### ISSUE THREAD

**Issue by dustycelia** [HTBox/crisischeckin#286]
Getting this message when trying to register for clientcheckin.

Server Error in '/' Application.

The SMTP server requires a secure connection or the client was not authenticated. The server response was: 5.5.1 Authentication Required. Learn more at

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.Net.Mail.SmtpException: The SMTP server requires a secure connection or the client was not authenticated. The server response was: 5.5.1 Authentication Required. Learn more at

Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace: 

[SmtpException: The SMTP server requires a secure connection or the client was not authenticated. The server response was: 5.5.1 Authentication Required. Learn more at]
   System.Net.Mail.MailCommand.CheckResponse(SmtpStatusCode statusCode, String response) +1525339
   System.Net.Mail.MailCommand.Send(SmtpConnection conn, Byte[] command, MailAddress from, Boolean allowUnicode) +46
   System.Net.Mail.SmtpTransport.SendMail(MailAddress sender, MailAddressCollection recipients, String deliveryNotify, Boolean allowUnicode, SmtpFailedRecipientException& exception) +88
   System.Net.Mail.SmtpClient.Send(MailMessage message) +1852
   Services.SmtpMessageSender.SendMessage(Message message, IReadOnlyCollection`1 recipients, String senderDisplayName) +236
   Services.MessageCoordinator.SendMessage(Message message, List`1 recipients, String senderDisplayName) +107
   Services.MessageService.SendMessage(Message message, Person recipient, String senderDisplayName) +115
   crisicheckinweb.Controllers.AccountController.Register(RegisterModel model) +432
   lambda_method(Closure , ControllerBase , Object[] ) +104
   System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters) +14
   System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters) +156
   System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters) +27
   System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState) +22
   System.Web.Mvc.Async.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult) +29
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult) +32
   System.Web.Mvc.Async.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d() +50
   System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +225
   System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +225
   System.Web.Mvc.Async.<>c__DisplayClass33.<BeginInvokeActionMethodWithFilters>b__32(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult) +34
   System.Web.Mvc.Async.<>c__DisplayClass2b.<BeginInvokeAction>b__1c() +26
   System.Web.Mvc.Async.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult) +100
   System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) +27
   System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState) +13
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +36
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +54
   System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +39
   System.Web.Mvc.Controller.<BeginExecute>b__15(IAsyncResult asyncResult, Controller controller) +12
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +28
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +54
   System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +29
   System.Web.Mvc.Controller.System.Web.Mvc.Async.IAsyncController.EndExecute(IAsyncResult asyncResult) +10
   System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState) +21
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +36
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +54
   System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +31
   System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result) +9
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +9651188
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +155

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.0.30319.36215

**Comment by BanksySan** [comment]
Could this be related to #296 & #295?

**Comment by BillWagner** [comment]
Yes, and if you want to work on this, @tonysurma and I have had some conversations on this.  Here's all the history:

I investigated the issues on our staging site this morning.  The root cause is that we've mixed two goals: We want our staging site running as close to the production code as possible, and we want our staging site to be public and open for anyone to test any of the features.

This causes problems when we get to email.  A core feature of the crisis checkin app is to facilitate communication between volunteers, coordinators, and administrators. This includes email. We've turned that off on the staging site: the SmtpCilent is not configured.  Recently, we added email confirmation to the registration page. Now, you can't register on the staging site. :disappointed:  

This now gets to a question about what we want on the staging site:


If this is built in debug mode, we don’t send any emails, but we write the email contents to a local folder.


In the ‘live’ site, we send emails.


In the staging site, we try to send emails (because it’s not a debug build), but we crash because the SmtpServices are not configured in the Azure portal.


At one point, we’d decided not to send emails on the staging site, because we use the default administrator password there. One could send emails to anyone that registered.


But wait, now we have turned on the “send an email and click to confirm registration” feature in ASp.NET. That means (I think) that we want our staging site to act like the ‘real’ site.


Proposal:


I believe we want the staging site to be as close to the live site as possible. That means leaving the email on, and sending registration emails when someone registers. In order to avoid confusion, here is the task list, as I see it:


change the admin password on the live staging site (it’s currently the default password in the source code)

Make code changes so that the From: address on the email, and a label on the subject, indicate whether an email is from the staging or live site.

Let our test and user community know how both sites are configured and how to distinguish email from the different sites.


The alternative would be to turn off the email link for registration on the staging site, which I believe means the staging site is less useful as a test installation.

We went with the first proposal.  Here are the tasks:

1. Add the correct configuration in the mailSettings node (or place different information in the Azure Portal)l for both Release and Staging.

2. Add a new new key for the [Subject] text to preface emails on staging with the STAGING TEST key.

3. Update the SendMessage method in SmtpMessageSender.cs to find that Subject text and update if necessary.

4. Update the RegisterServices method in NinjectWebCommon.cs to find and use the correct services for sending mail.

@BanksySan If you want to work on the code portions, @tonysurma and I will then update the Azure portal with the proper keys for both staging and production.

**Comment by kinetiq** [comment]
@BillWagner Apologies that I missed this when I opened my case, it's a very clear duplicate.

This does seem like a very straightforward place for me to jump in... I'm familiar with Ninject and so on, and your notes look good.

Let me give the project a quick look before I make a commitment to you. Give me until the end of the day.

**Comment by kinetiq** [comment]
@BillWagner Okay, I'm in. I will get this done. 

BTW: you probably don't know the name Kinetiq, but this is Brian MacKay from App vNext.

**Comment by kinetiq** [comment]
@BillWagner That should do it! 

In the pull request you will notice that there are some stylistic questions I wasn't certain about. If you have a particular way you want to handle configuration (facade, etc), let me know and I will be happy to implement it. 

To test this, I spoofed the staging web.config  (using my personal email credentials) and switched to the new Staging configuration to turn off your DEBUG directive. These are not absolutely perfect test conditions, but I'm fairly confident that it's at least very close.

**One final note:** you asked for a [STAGING] tag in the event of an email from staging, but did not mention the possibility of an email coming out of the development  environment. It could happen and that will result in [DEVELOPMENT] showing up. Production, of course, does not get a tag.
