### ISSUE TITLE
Possible encoding error in confirmation emails

### ISSUE THREAD

**Issue by BanksySan** [HTBox/crisischeckin#295]
Looking at the `.eml` files, the links are broken:

    X-Sender: "CrisisCheckin" <no-reply@crisischeckin.com>
    X-Receiver: "OVn7ZMfirstName OVn7ZMlastName" <OVn7ZM@example.com>
    MIME-Version: 1.0
    From: "CrisisCheckin" <no-reply@crisischeckin.com>
    To: "OVn7ZMfirstName OVn7ZMlastName" <OVn7ZM@example.com>
    Date: 14 Jun 2015 20:12:25 +0100
    Subject: CrisisCheckin - Activate your account
    Content-Type: text/html; charset=us-ascii
    Content-Transfer-Encoding: quoted-printable

    <p>Click on the following link to activate your account: <a href=3D=
    'http://localhost:2077/Account/ConfirmAccount?token=3DAtmTRegKSMV=
    UGrHGE1doDw2'>http://localhost:2077/Account/ConfirmAccount?token=3D=
    AtmTRegKSMVUGrHGE1doDw2</a></p>

Look at ` <a href=3D=`, 3d is the ASCII hex value for `=`, the encoding is set to `us-ascii`

Is anyone else having this problem?  I assume that the emails do work and that this is just a symptom of the email being outputting to the file system.

_Should we be using Unicode for emails?_

**Comment by TravCav** [comment]
@BillWagner This is indeed related to #297 and still happening.  However everything is working as intended and nothing needs changed. The email is "Content-Type: text/html; charset=us-ascii" and assuming your client can handle html emails everything works like it's supposed to.  This is only a problem if you're opening up the file in a text editor. I tried setting outlook to open all emails as plain text and it still shows the correct decoded link.  I don't have an email client that can't handle html type email, but i'll test with that if anyone can recommend one.  I'd close #295 and #297 since everything is working like it's supposed to, unless there's a bigger issue that needs solved here.
