### ISSUE TITLE
Staging site code is out of date - Disaster/List page has error "DataReader open"

### ISSUE THREAD

**Issue by RyanBetker** [HTBox/crisischeckin#330]
Login as Administrator and you'll get the error right away.
This is an issue because folks trying to learn about what the site does would be immediately stopped from exploring it further.

Link to Page: https://crisischeckin-d.azurewebsites.net/Disaster/List
Good news is that it isn't an issue with that master branch locally though :)

This **can be fixed by an Admin pushing out the master branch** to the site: https://crisischeckin-d.azurewebsites.net/

**Comment by BillWagner** [comment]
@RyanBetker Thanks for investigating this. It turns out that it did need a code change (in the DisasterController). The way the list of disasters was being constructed, it ended up having two data readers open at the same time.

What's confusing to me is that the previous code did work locally.

(BTW, the -d site, https://crisischeckin-d.azurewebsites.net is automatically deployed whenever we merge a pull request. I'm not sure how we missed seeing this regression.)
