### ISSUE TITLE
Add Organization Resources Functionality

### ISSUE THREAD

**Issue by NaveenP94** [HTBox/crisischeckin#473]
We need to create a entity (and associated db & ui changes) that holds the Resources of the Organizations that are checked in.  E.g. An Organization can check in 10 Pickup Trucks for next week to a particular location. Logically similar to a volunteer checking in only this is for resources.

Should include data below:

- Name of the resource (non standardized)
- Type of resource  (standardized to "Food", "Water", "Medical", "Shelter", "Heavy Machines" -- we will make this editable/standardized later)
- Description (non standardized multi-line text )
- Allocator ( name of the organization that is offering this resource should be a reference to the appropriate Organization) #470 
- Availability (Date range)
- Location (simple address for now) 
- Quantity ( this will require some further logic to choose the units associated with this based on the type, for now we will just have this as a numeric value for simplicity) 
- Status ( standardized "Available", "En Route", "Delivered")
- Disaster ( this will be used to sort and search for resource by disaster similarly to how we sort and search volunteers by disaster)

**Comment by andrewhart098** [comment]
I am working on this.

**Comment by tonysurma** [comment]
thx for picking this up.  I have invited you to the repo so I can assign items to you etc.

**Comment by andrewhart098** [comment]
I'm somewhat confused as to how to handle the Allocator property.  Currently, a user does not need to be tied to an organization.  At least the 'Administrator' and 'Test User' that are added to the database are not tied to an organization.  My plan was to have the resource tied to the organization of the user that created the resource entry.  Since it might be the case where a user does not have an organization, I don't know if I should simply ignore the Allocator property for now, introduce logic to check whether the user is tied to an organization or hold off on this issue until the Organization-Person link is firmly established in the code.

**Comment by tonysurma** [comment]
Thx, ignore allocater for now to proceed and we will have to create an issue to tie all users to orgs.  That is leftover from when we didn't have orgs but every user must be in an org and the sample data could make an htbox org for admin and 'Test non profit' org for user sample account.

Thx for contributing

**Comment by andrewhart098** [comment]
I believe this issue can be closed now that #658 has been merged.

**Comment by BillWagner** [comment]
Thanks @andrewhart098 Closing now.
