### ISSUE TITLE
Edits for Resources Table & View

### ISSUE THREAD

**Issue by NaveenP94** [HTBox/crisischeckin#490]
The following are changes that are needed for the Resources table on the "View Checkins" page:

- [x] Add Time Stamp to when entry is made (When someone checks in a resource we want the time of entry displayed in the table) *the user should not have to manually input the time rather pull the time when the server is pinged with the request

- [x] Display Name of Organization & Name of user that checked in resource under "Organization" column of the Resources table. ex: CDC, John Smith

- [x] Add to "Type" column the label "Hazard" , "Pamphlets Delivered", "Medical Services"

**Comment by mjmilan** [comment]
2ns and 3rd tasks addressed by #495

**Comment by tonysurma** [comment]
Thank you @mjmilan for the quick turnaround!

**Comment by mjmilan** [comment]
No problem...

**Comment by mjmilan** [comment]
The first task gives rise to some questions... Does it really make sense that we set the time according to the time when the transaction is made? If as a user I am saying that something will be available from next Tuesday until next Friday, does anyone care about the fact that I happen to be doing this at 14:17 the previous Monday?

Why is 14:17 considered as special?

Would it not make more sense to provide UI functionality so that they could choose the time, but  default it to something like 00:00?

**Comment by tonysurma** [comment]
Great question, in the long run we may be adding times to the commitments (pending discussions as for most all it will stay at the day level)

For now we want to know when theses are checked in for two reasons: timeliness/staleness of data and also as current excercises are looking to run this in 'real time' and the timestamps will help.

Separately I am editing the issue as it should actually not be for both start and end date and just be an 'entered date' as there aren't times for the start/end yet

**Comment by tonysurma** [comment]
For #3 this is handled by data entry that we will do for the exercise

Thanks again

**Comment by tonysurma** [comment]
first item is complete as well - verified
