### ISSUE TITLE
Application is uncomfortable to use on mobile phone

### ISSUE THREAD

**Issue by miketull** [HTBox/crisischeckin#633]
P1, virtual

It seems likely to me that the application will be used on a mobile device in the field.  Because I’m running out of the time I’ve been allowed to do this, I can’t provide a detailed description.  My summary comment is that on the iPhone 6, I was very uncomfortable trying to use the application due to issues with UI, field sizes, and responsiveness.

**Comment by NaveenP94** [comment]
Thank you for your comment, We are aware of the difficulty using the application on a mobile browser that is why one of our P1 issues are to move to a multipage view so we can have more pages with less information on each page, this is our quick fix solution since we don't have the resources to build a true mobile app at this time. Once we move to a multipage view we want to add short cuts to be able to navigate between pages faster from any page, then we can tackle button layout and textbox sizes etc. please see issue #500
